# Generated by Django 6.0.4 on 2026-04-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date', 'title']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterModelTable(
            name='movie',
            table=None,
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='movies.genre'),
        ),
    ]
